name: foco
version: git
summary: Use the video scene and make the Yeelight spot adapt that color.
icon: foco.svg
type: app
title: foco
description: |
  Use the video scene and make the Yeelight spot adapt that color.

confinement: devmode
base: core18

parts:
  foco:
    plugin: nodejs
    source: .

apps:
  foco:
    command: foco
    plugs: [network-bind]
    daemon: simple
    restart-condition: always
